PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <http://www.gdpr-ethics/linked-datasets#>


SELECT ?Dataset
WHERE {
 	?Val    rdf:a    ?"true"^^xsd:boolean   .

 	{   ?Dataset 	base:hasEmbryoRelatedVocab 	?Val  . }
OPTIONAL
    { ?Dataset 	base:hasPersonalData 	?Val  }

}
